### ISSUE TITLE
i have an error while opening my website

### ISSUE THREAD

**Issue by Lsunix456** [MathieuAR-GDPSFH/panel#1]
so, when i open my website just pops out this:

" Warning: require(../auth/check_auth.php): failed to open stream: No such file or directory in /storage/ssd5/800/20179800/public_html/index.php on line 4

Warning: require(../auth/check_auth.php): failed to open stream: No such file or directory in /storage/ssd5/800/20179800/public_html/index.php on line 4

Fatal error: require(): Failed opening required '../auth/check_auth.php' (include_path='.:/usr/share/pear:/usr/share/php') in /storage/ssd5/800/20179800/public_html/index.php on line 4 "

Pls help

**Comment by MathieuARS** [comment]
Check if the "check_auth.php" file is in the auth folder

**Comment by Lsunix456** [comment]
thanks!
